# Generated by Django 3.1 on 2019-11-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggiehub', '0001_initial'),
    ]

    operations = [
       
    ]
